FROM php:8.3-cli

RUN apt-get update && apt-get install -y \
    git curl unzip libicu-dev libzip-dev libpng-dev libonig-dev \
    && docker-php-ext-install pdo_mysql intl mbstring zip \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer

WORKDIR /app
